# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yinsen Miao
tagline:          'Tech Blogs'
description:      'Powered by <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:              http://yinsenm.github.io/
#baseurl:          'http://yinsenm.github.io/'
paginate:         1

author:
  name:           'Yinsen Miao'
  url:             http://yinsen.blogs.rice.edu/

# Custom vars
version:          1.0.2

github:
  repo:           https://github.com/yinsenm